name: task_numismatics
description: Login and Sign Up UI - Flutter


publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

  cupertino_icons: ^1.0.2
  get:
  line_icons: ^2.0.1
  animate_do: ^2.1.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.2.1
  provider: ^6.0.2
  sign_button: ^2.0.2
#  cloud_firestore: any
#  firebase_admob: 0.5.5
#  firebase_auth: 0.5.11
#  google_sign_in: 3.0.4
#  firebase_analytic: 1.0.1
#  firebase_core: 0.2.4
  firebase_database: any
#  firebase_dynamic_links: 0.02
#  firebase_messaging: 1.0.2
#  firebase_performance: any
#  firebase_remote_config: any
#  firebase_storage: any
#  font_awesome_flutter: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
